[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = qio
board_build.f_cpu = 240000000L
lib_deps = 
    adafruit/Adafruit BME280 Library
    adafruit/DHT sensor library
    olikraus/U8g2
    adafruit/Adafruit Unified Sensor
build_flags = 
    -DCORE_DEBUG_LEVEL=0
