[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = qio
board_build.f_cpu = 240000000L
lib_deps = 
    adafruit/Adafruit BME280 Library@^2.2.4
    adafruit/DHT sensor library@^1.4.6
    olikraus/U8g2@^2.35.4
    adafruit/Adafruit Unified Sensor@^1.1.14
build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
